import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError, timeout } from 'rxjs/operators';
import { environment } from '../../environments/environment';
import { JobSeeker, JobOffer } from '../types';

// Import jsPDF
import jsPDF from 'jspdf';

export interface GenerateCVRequest {
  jobSeeker: JobSeeker;
  jobOffer: JobOffer;
  format: 'ats' | 'modern' | 'creative';
}

export interface GeneratedCVSection {
  title: string;
  content: string;
  order: number;
}

export interface GenerateCVResponse {
  sections: GeneratedCVSection[];
  summary: string;
  optimizedSkills: string[];
  atsScore: number;
  keywords: string[];
  rawContent: string;
}

@Injectable({
  providedIn: 'root'
})
export class CvGenerationService {
  private apiUrl = "http://localhost:3001";

  constructor(private http: HttpClient) {}

  /**
   * Génère un CV optimisé ATS
   */
  generateATSCV(request: GenerateCVRequest): Observable<GenerateCVResponse> {
    return this.http.post<GenerateCVResponse>(
      `${this.apiUrl}/cv-generation/generate-ats-cv`,
      request
    ).pipe(
      timeout(45000),
      catchError(this.handleError)
    );
  }

  /**
   * Vérifie la santé du service
   */
  healthCheck(): Observable<{ status: string; service: string }> {
    return this.http.get<{ status: string; service: string }>(
      `${this.apiUrl}/cv-generation/health`
    ).pipe(
      timeout(5000),
      catchError(this.handleError)
    );
  }

  /**
   * Génère un PDF à partir du contenu CV
   */
  generatePDF(cvResponse: GenerateCVResponse, jobSeeker: JobSeeker, jobOffer: JobOffer): void {
    try {
      const pdf = new jsPDF();
      
      // Configuration
      const margin = 20;
      let yPosition = margin;
      const lineHeight = 7;
      const pageHeight = pdf.internal.pageSize.height;
      
      // Couleurs
      const primaryColor = [41, 128, 185]; // Bleu
      const secondaryColor = [52, 73, 94]; // Gris foncé
      
      // En-tête du CV
      pdf.setFontSize(20);
      pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      pdf.text(jobSeeker.fullName.toUpperCase(), margin, yPosition);
      yPosition += lineHeight + 5;
      
      pdf.setFontSize(12);
      pdf.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
      pdf.text(jobSeeker.title || 'Professional', margin, yPosition);
      yPosition += lineHeight;
      
      // Informations de contact
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      const contactInfo = [
        jobSeeker.email,
        jobSeeker.phone_number,
        jobSeeker.nationality
      ].filter(Boolean).join(' | ');
      
      pdf.text(contactInfo, margin, yPosition);
      yPosition += lineHeight + 10;
      
      // Score ATS
      pdf.setFontSize(11);
      pdf.setTextColor(39, 174, 96); // Vert
      pdf.text(`ATS Score: ${cvResponse.atsScore}/100`, margin, yPosition);
      yPosition += lineHeight + 5;
      
      // Sections du CV
      const sections = cvResponse.sections.sort((a, b) => a.order - b.order);
      
      sections.forEach(section => {
        // Vérifier si on doit ajouter une nouvelle page
        if (yPosition > pageHeight - 40) {
          pdf.addPage();
          yPosition = margin;
        }
        
        // Titre de section
        pdf.setFontSize(12);
        pdf.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        pdf.setFont('helvetica', 'bold'); // CORRECTION : Utiliser 'helvetica' au lieu de undefined
        pdf.text(section.title.toUpperCase(), margin, yPosition);
        yPosition += lineHeight + 2;
        
        // Ligne de séparation
        pdf.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        pdf.line(margin, yPosition, margin + 50, yPosition);
        yPosition += 5;
        
        // Contenu de section
        pdf.setFontSize(10);
        pdf.setTextColor(0, 0, 0);
        pdf.setFont('helvetica', 'normal'); // CORRECTION : Utiliser 'helvetica' au lieu de undefined
        
        const contentLines = this.splitTextIntoLines(pdf, section.content, 170);
        contentLines.forEach(line => {
          if (yPosition > pageHeight - 20) {
            pdf.addPage();
            yPosition = margin;
          }
          pdf.text(line, margin, yPosition);
          yPosition += lineHeight;
        });
        
        yPosition += 10; // Espacement entre sections
      });
      
      // Pied de page
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Generated by Jobify AI - ATS Optimized CV for ${jobOffer.title} at ${jobOffer.company}`,
        margin,
        pageHeight - 10
      );
      
      // Télécharger le PDF
      const fileName = `ATS_CV_${jobSeeker.fullName.replace(/\s+/g, '_')}_${jobOffer.title.replace(/\s+/g, '_')}.pdf`;
      pdf.save(fileName);
      
    } catch (error) {
      console.error('PDF generation error:', error);
      throw new Error('Failed to generate PDF. Please try again.');
    }
  }

  /**
   * Divise le texte en lignes pour le PDF
   */
  private splitTextIntoLines(pdf: jsPDF, text: string, maxWidth: number): string[] {
    const lines: string[] = [];
    const sentences = text.split('\n');
    
    sentences.forEach(sentence => {
      const words = sentence.split(' ');
      let currentLine = '';
      
      words.forEach(word => {
        const testLine = currentLine ? `${currentLine} ${word}` : word;
        const testWidth = pdf.getTextWidth(testLine);
        
        if (testWidth > maxWidth) {
          if (currentLine) {
            lines.push(currentLine);
          }
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      });
      
      if (currentLine) {
        lines.push(currentLine);
      }
    });
    
    return lines;
  }

  /**
   * Gestion des erreurs
   */
  private handleError(error: HttpErrorResponse) {
    let errorMessage = 'An unknown error occurred';
    
    if (error.error instanceof ErrorEvent) {
      errorMessage = `Client error: ${error.error.message}`;
    } else {
      switch (error.status) {
        case 0:
          errorMessage = 'Unable to connect to CV generation service.';
          break;
        case 400:
          errorMessage = 'Invalid CV generation request. Please check all required fields.';
          break;
        case 500:
          errorMessage = 'CV generation service is temporarily unavailable.';
          break;
        case 504:
          errorMessage = 'CV generation timeout. The AI is taking longer than expected.';
          break;
        default:
          errorMessage = `CV generation failed: ${error.status} - ${error.message}`;
      }
    }
    
    console.error('CV generation error:', error);
    return throwError(() => new Error(errorMessage));
  }
}